package com.smbvt.bst.applewatchhomeuiandroid.utils

import android.content.Context
import com.smbvt.bst.applewatchhomeuiandroid.R
import com.smbvt.bst.applewatchhomeuiandroid.domain.Countries
import com.smbvt.bst.applewatchhomeuiandroid.domain.Country
import com.smbvt.bst.applewatchhomeuiandroid.domain.Menu
import com.smbvt.bst.applewatchhomeuiandroid.domain.MenuItems

object DataUtils {

    fun getMenuItems(context: Context): MenuItems {
        return MenuItems(
            listOf(
                Menu(0, "menu_1", R.drawable.menu_1),
                Menu(0, "menu_2", R.drawable.menu_2),
                Menu(0, "menu_3", R.drawable.menu_3),
                Menu(0, "menu_4", R.drawable.menu_4),
                Menu(0, "menu_5", R.drawable.menu_5),
                Menu(0, "menu_6", R.drawable.menu_6),
                Menu(0, "menu_7", R.drawable.menu_7),
                Menu(0, "menu_8", R.drawable.menu_8),
                Menu(0, "menu_9", R.drawable.menu_9),
                Menu(0, "menu_10", R.drawable.menu_10),
                Menu(0, "menu_11", R.drawable.menu_11),
                Menu(0, "menu_12", R.drawable.menu_12),
                Menu(0, "menu_13", R.drawable.menu_13),
                Menu(0, "menu_14", R.drawable.menu_14),
                Menu(0, "menu_15", R.drawable.menu_15),
                Menu(0, "menu_16", R.drawable.menu_16),
                Menu(0, "menu_17", R.drawable.menu_17),
                Menu(0, "menu_18", R.drawable.menu_18),
                Menu(0, "menu_19", R.drawable.menu_19),
                Menu(0, "menu_20", R.drawable.menu_20),
                Menu(0, "menu_21", R.drawable.menu_21),
                Menu(0, "menu_22", R.drawable.menu_22),
                Menu(0, "menu_23", R.drawable.menu_23),
                Menu(0, "menu_1", R.drawable.menu_1),
                Menu(0, "menu_2", R.drawable.menu_2),
                Menu(0, "menu_3", R.drawable.menu_3),
                Menu(0, "menu_4", R.drawable.menu_4),
                Menu(0, "menu_5", R.drawable.menu_5),
                Menu(0, "menu_6", R.drawable.menu_6),
                Menu(0, "menu_7", R.drawable.menu_7),
                Menu(0, "menu_8", R.drawable.menu_8),
                Menu(0, "menu_9", R.drawable.menu_9),
                Menu(0, "menu_10", R.drawable.menu_10),
                Menu(0, "menu_11", R.drawable.menu_11),
                Menu(0, "menu_12", R.drawable.menu_12),
                Menu(0, "menu_13", R.drawable.menu_13),
                Menu(0, "menu_14", R.drawable.menu_14),
                Menu(0, "menu_15", R.drawable.menu_15),
                Menu(0, "menu_16", R.drawable.menu_16),
                Menu(0, "menu_17", R.drawable.menu_17),
                Menu(0, "menu_18", R.drawable.menu_18),
                Menu(0, "menu_19", R.drawable.menu_19),
                Menu(0, "menu_20", R.drawable.menu_20),
                Menu(0, "menu_21", R.drawable.menu_21),
                Menu(0, "menu_22", R.drawable.menu_22),
                Menu(0, "menu_23", R.drawable.menu_23),
            )
        )
    }

    fun getCountries(): Countries {
        return Countries(
            listOf(
                Country(0, "ad", R.drawable.ad),
                Country(0, "ae", R.drawable.ae),
                Country(0, "af", R.drawable.af),
                Country(0, "ag", R.drawable.ag),
                Country(0, "ai", R.drawable.ai),
                Country(0, "al", R.drawable.al),
                Country(0, "am", R.drawable.am),
                Country(0, "ao", R.drawable.ao),
                Country(0, "aq", R.drawable.aq),
                Country(0, "ar", R.drawable.ar),
                Country(0, "at", R.drawable.at),
                Country(0, "au", R.drawable.au),
                Country(0, "aw", R.drawable.aw),
                Country(0, "ax", R.drawable.ax),
                Country(0, "az", R.drawable.az),
                Country(0, "ba", R.drawable.ba),
                Country(0, "bb", R.drawable.bb),
                Country(0, "bd", R.drawable.bd),
                Country(0, "be", R.drawable.be),
                Country(0, "bf", R.drawable.bf),
                Country(0, "bg", R.drawable.bg),
                Country(0, "bh", R.drawable.bh),
                Country(0, "bi", R.drawable.bi),
                Country(0, "bj", R.drawable.bj),
                Country(0, "bl", R.drawable.bl),
                Country(0, "bm", R.drawable.bm),
                Country(0, "bn", R.drawable.bn),
                Country(0, "bo", R.drawable.bo),
                Country(0, "bq", R.drawable.bq),
                Country(0, "br", R.drawable.br),
                Country(0, "bs", R.drawable.bs),
                Country(0, "bt", R.drawable.bt),
                Country(0, "bv", R.drawable.bv),
                Country(0, "bw", R.drawable.bw),
                Country(0, "by", R.drawable.by),
                Country(0, "bz", R.drawable.bz),
                Country(0, "ca", R.drawable.ca),
                Country(0, "cc", R.drawable.cc),
                Country(0, "cd", R.drawable.cd),
                Country(0, "cf", R.drawable.cf),
                Country(0, "cg", R.drawable.cg),
                Country(0, "ch", R.drawable.ch),
                Country(0, "ci", R.drawable.ci),
                Country(0, "ck", R.drawable.ck),
                Country(0, "cl", R.drawable.cl),
                Country(0, "cm", R.drawable.cm),
                Country(0, "cn", R.drawable.cn),
                Country(0, "co", R.drawable.co),
                Country(0, "cr", R.drawable.cr),
                Country(0, "cu", R.drawable.cu),
                Country(0, "cv", R.drawable.cv),
                Country(0, "cw", R.drawable.cw),
                Country(0, "cx", R.drawable.cx),
                Country(0, "cy", R.drawable.cy),
                Country(0, "cz", R.drawable.cz),
                Country(0, "de", R.drawable.de),
                Country(0, "dj", R.drawable.dj),
                Country(0, "dk", R.drawable.dk),
                Country(0, "dm", R.drawable.dm),
                Country(0, "dz", R.drawable.dz),
                Country(0, "ec", R.drawable.ec),
                Country(0, "ee", R.drawable.ee),
                Country(0, "eg", R.drawable.eg),
                Country(0, "eh", R.drawable.eh),
                Country(0, "er", R.drawable.er),
                Country(0, "es", R.drawable.es),
                Country(0, "et", R.drawable.et),
                Country(0, "fi", R.drawable.fi),
                Country(0, "fj", R.drawable.fj),
                Country(0, "fk", R.drawable.fk),
                Country(0, "fm", R.drawable.fm),
                Country(0, "fo", R.drawable.fo),
                Country(0, "fr", R.drawable.fr),
                Country(0, "ga", R.drawable.ga),
                Country(0, "gb", R.drawable.gb),
                Country(0, "gd", R.drawable.gd),
                Country(0, "ge", R.drawable.ge),
                Country(0, "gf", R.drawable.gf),
                Country(0, "gg", R.drawable.gg),
                Country(0, "gh", R.drawable.gh),
                Country(0, "gi", R.drawable.gi),
                Country(0, "gl", R.drawable.gl),
                Country(0, "gm", R.drawable.gm),
                Country(0, "gn", R.drawable.gn),
                Country(0, "gp", R.drawable.gp),
                Country(0, "gq", R.drawable.gq),
                Country(0, "gr", R.drawable.gr),
                Country(0, "gs", R.drawable.gs),
                Country(0, "gt", R.drawable.gt),
                Country(0, "gu", R.drawable.gu),
                Country(0, "gw", R.drawable.gw),
                Country(0, "gy", R.drawable.gy),
                Country(0, "hk", R.drawable.hk),
                Country(0, "hm", R.drawable.hm),
                Country(0, "hn", R.drawable.hn),
                Country(0, "hr", R.drawable.hr),
                Country(0, "ht", R.drawable.ht),
                Country(0, "hu", R.drawable.hu),
                Country(0, "id", R.drawable.id),
                Country(0, "ie", R.drawable.ie),
                Country(0, "il", R.drawable.il),
                Country(0, "im", R.drawable.im),
                Country(0, "io", R.drawable.io),
                Country(0, "iq", R.drawable.iq),
                Country(0, "ir", R.drawable.ir),
                Country(0, "it", R.drawable.it),
                Country(0, "je", R.drawable.je),
                Country(0, "jm", R.drawable.jm),
                Country(0, "jo", R.drawable.jo),
                Country(0, "jp", R.drawable.jp),
                Country(0, "ke", R.drawable.ke),
                Country(0, "kg", R.drawable.kg),
                Country(0, "kh", R.drawable.kh),
                Country(0, "ki", R.drawable.ki),
                Country(0, "km", R.drawable.km),
                Country(0, "kn", R.drawable.kn),
                Country(0, "kp", R.drawable.kp),
                Country(0, "kr", R.drawable.kr),
                Country(0, "kw", R.drawable.kw),
                Country(0, "ky", R.drawable.ky),
                Country(0, "kz", R.drawable.kz),
                Country(0, "la", R.drawable.la),
                Country(0, "lb", R.drawable.lb),
                Country(0, "lc", R.drawable.lc),
                Country(0, "li", R.drawable.li),
                Country(0, "lk", R.drawable.lk),
                Country(0, "lr", R.drawable.lr),
                Country(0, "ls", R.drawable.ls),
                Country(0, "lt", R.drawable.lt),
                Country(0, "lu", R.drawable.lu),
                Country(0, "lv", R.drawable.lv),
                Country(0, "ly", R.drawable.ly),
                Country(0, "ma", R.drawable.ma),
                Country(0, "mc", R.drawable.mc),
                Country(0, "md", R.drawable.md),
                Country(0, "me", R.drawable.me),

            )
        )
    }
}